config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'foods#index'

  resources :foods, only: [:index, :new, :create, :destroy]

  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :recipes, except: [:update] do
    member do
      patch 'toggle_public'
      patch 'update_times'
      get 'new_step', to: 'recipe_steps#new'
      post 'create_step', to: 'recipe_steps#create'
    end

    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end

  get 'general_shopping_list', to: 'foods#general_shopping_list', as: 'general_shopping_list'

  resources :public_recipes, only: [:index]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :foods, through: :recipe_foods
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  def editing_times?
    preparation_time.nil? && cooking_time.nil?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy toggle_public add_food create_food]

  def index
    @recipes = current_user.recipes
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipes_url, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    @recipe_foods = @recipe.recipe_foods
    @user = current_user
    @food = Food.new if current_user == @recipe.user
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if current_user == @recipe.user
      @recipe.destroy
      redirect_to recipes_url, notice: 'Recipe was successfully deleted.'
    else
      redirect_to recipes_url, alert: 'You are not authorized to delete this recipe.'
    end
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])

    if current_user == @recipe.user
      @recipe.toggle!(:public)

      notice_message = if @recipe.public?
                         'Recipe is now public.'
                       else
                         'Recipe is now private.'
                       end
    else
      notice_message = 'You are not authorized to manage this recipe.'
    end

    redirect_to recipe_path(@recipe), notice: notice_message
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def add_ingredient
    @recipe = Recipe.find(params[:id])
    @food = Food.new
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
    render 'public_index'
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end

  def food_params
    params.require(:food).permit(:name, :quantity, :unit)
  end

  def shopping_list
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="recipecontainer">
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, 'error') %> prohibited this recipe from being saved:</h2>

      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div >
  <%= f.label :preparation_time %> in hour
  <%= f.number_field :preparation_time %>
</div>
<div>
  <%=f.label :cooking_time%> in hour
  <%= f.number_field :cooking_time %>
</div>
<div>
  <%= f.check_box :public%>
  <%= f.label :public %>
</div>
 
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>
</div>

app/views/recipes/_recipe_details.html.erb
<!-- Display recipe details -->

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render 'form' %>
<%= link_to 'Show', @recipe %>

app/views/recipes/index.html.erb
<h1> Recipes List</h1>
<div class="recipeDiv">
<% @recipes.each do |recipe| %>
	<div class="recipe">
	<div class="recipe-header">
	  <p class="recipe_name"><%= link_to recipe.name, recipe_path(recipe) %></p>
	  <span class="Delete"><%= button_to "Remove", recipe_path(recipe.id), method: :delete, data: { confirm: "Are you sure?" } %></span>
	</div>
	<div class="recipe-content">
	  <p class="recipe-description"><%= recipe.description %></p>
	</div>
  </div>  
<% end %>

<%= link_to 'Add New Recipe', new_recipe_path, class: 'new-recipe-link' %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>
<%= link_to 'Back', recipes_path, class: 'back-link' %>

app/views/recipes/show.html.erb
<div class="recipedetails">
  <h1><%= @recipe.name %></h1>

  <% if current_user == @recipe.user || @recipe.public %>
    <%= render 'recipe_details', recipe: @recipe %>
  <% else %>
    <p>This recipe is private.</p>
  <% end %>

  <div class="content-container">
    <div class="left-section">
      <div class="names">
        <p class="time"><strong><%= @recipe.editing_times? ? @recipe.preparation_time : "preparation_time: #{@recipe.preparation_time} hours" %></p>
        <p class="time"><%= @recipe.editing_times? ? @recipe.cooking_time : "cooking_time: #{@recipe.cooking_time} hours" %></p>
        <p class="steps">Steps go here...</p>
      </div>
    </div>

    <div class="right-section">
      <div class="buttons" id="is_public">
        <%= button_to(@recipe.public? ? "Make it Private" : "Make it Public", toggle_public_recipe_path(@recipe), method: :patch, class: "toggle-button #{'private' unless @recipe.public?}") %>
      </div>
    </div>
  </div>
  <div class="buttons">
  <%= link_to "Generate shopping list", general_shopping_list_path, class: 'btn btn-action' %>
  <% if current_user == @recipe.user %>
    <%= link_to "Add ingredient", new_recipe_recipe_food_path(recipe_id: @recipe.id), class: 'btn1 btn-action' %>
  <% end %>
</div>
<div class="line-divider"></div>
  <% if @recipe.recipe_foods.includes(:food).any? %>
    <div class="tableDivx">
      <table>
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Value</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe.recipe_foods.includes(:food).each do |recipe_food| %>
            <tr>
              <td><%= recipe_food.food.name %></td>
              <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
              <td>$ <%= recipe_food.quantity * recipe_food.food.price %></td>
              <td class="recipe-food-actions">
			  <% if current_user == @recipe.user %>
			  <%= link_to 'Modify', edit_recipe_recipe_food_path(recipe_food) %> 
			 <span class="Delete"><%= button_to  'Remove',  recipe_recipe_food_path(recipe_food), class: "btn-delete", method: :delete, data: { confirm: 'Are you sure?' } %></span>
			<% end %>
              </td>
            </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>