config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'foods#index'

  resources :foods, only: [:index, :new, :create, :destroy]

  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :recipes, except: [:update] do
    member do
      patch 'toggle_public'
      patch 'update_times'
      get 'new_step', to: 'recipe_steps#new'
      post 'create_step', to: 'recipe_steps#create'
    end

    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end

  get 'general_shopping_list', to: 'foods#general_shopping_list', as: 'general_shopping_list'

  resources :public_recipes, only: [:index]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = current_user.foods
  end

  def new
    @current_user = current_user
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      puts 'Food saved successfully!'
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      puts 'Food creation failed!'
      flash[:alert] = @food.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def set_food
    @food = current_user.foods.find_by(id: params[:id])
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    redirect_to foods_url
  end

  def general_shopping_list
    @recipes = current_user.recipes
    @general_food_list = current_user.foods
    @missing_food_items = []

    process_missing_food_items

    @total_food_items = @missing_food_items.sum { |item| item[:quantity_needed] }
    @total_price = @missing_food_items.sum { |item| item[:price] }
  end

  private

  def process_missing_food_items
    @recipes.each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        process_recipe_food(recipe_food)
      end
    end
  end

  def process_recipe_food(recipe_food)
    general_food = @general_food_list.find_by(id: recipe_food.food_id)
    return if general_food_exists_and_has_enough_quantity?(recipe_food, general_food)

    quantity_needed = calculate_quantity_needed(recipe_food, general_food)
    price = recipe_food.food.price * quantity_needed

    @missing_food_items << {
      food_name: recipe_food.food.name,
      quantity_needed:,
      price:
    }
  end

  def general_food_exists_and_has_enough_quantity?(recipe_food, general_food)
    !general_food.nil? && general_food.quantity >= recipe_food.quantity
  end

  def calculate_quantity_needed(recipe_food, general_food)
    recipe_food.quantity - (general_food.nil? ? 0 : general_food.quantity)
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/general_shopping_list.html.erb
<style>
  .shopping_list {
    text-align: center;
    margin: 20px;
  }

  h1 {
    color: #333;
  }

  .total {
    margin-bottom: 20px;
  }

  .total p {
    display: inline-block;
    margin: 0 10px;
  }

  table {
    width: 50%;
    margin: 0 auto;
    border-collapse: collapse;
    margin-top: 20px;
  }

  th, td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid #ddd;
  }

  th {
    background-color: #f2f2f2;
  }

  tbody tr:nth-child(even) {
    background-color: #f9f9f9;
  }

  tbody tr:hover {
    background-color: #f1f1f1;
  }

  p {
    color: black;
	font-size: 20px;
	font-weight: bold;
  }
</style>

<div class="shopping_list" id="shopping">
  <h1>Shopping List</h1>

  <% if @missing_food_items.any? %>
    <div class="total">
      <p>Amount of food to buy: <%= @total_food_items %></p>
      <p>Total value of food need: <%= @total_price %></p>
    </div>
    <div class="table">
      <table>
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @missing_food_items.each do |item| %>
            <tr>
              <td><%= item[:food_name] %></td>
              <td><%= item[:quantity_needed] %></td>
              <td>$<%= item[:price] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>No missing food items.</p>
  <% end %>
</div>

app/views/foods/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    h2 {
      text-align: center;
      color: #333;
    }

    .tableDiv {
      margin-top: 20px;
	  margin-left: 25%;
    }

    table {
      width: 60%;
      border-collapse: collapse;
      margin-top: 30px;
    }

    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }

    th {
      background-color: #f2f2f2;
    }

    .add-button {
      background-color: #4caf50;
      color: white;
      padding: 10px 15px;
      text-decoration: none;
      display: inline-block;
      border-radius: 5px;
	  margin-left: 50%;
    }

    .Remove {
      text-align: center;
    }

    p {
      text-align: center;
      color: #777;
    }
  </style>
</head>
<body>
  <h2>Available food</h2>
  <div class="tableDiv">
    <div id="public">
      <%= link_to 'Add Food', new_food_path, class: "add-button" %>
    </div>
    <% if @foods.any? %>
      <table>
        <thead>
          <tr>
            <th>Food </th>
            <th>Measurement unit</th>
            <th>Unit price</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td><%= food.name %></td>
              <td><%= food.measurement_unit %></td>
              <td>$<%= food.price %></td>
			  <td class="Remove"><%= button_to "Delete Food", food_path(food.id), method: :delete, data: { confirm: "Are you sure?" } %></td>
			</tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% else %>
      <p>No food for you.</p>
    <% end %>
  </div>
</body>
</html>

app/views/foods/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }

    h1 {
      text-align: center;
      color: #333;
    }

    .formcontainer {
      max-width: 400px;
      margin: 50px auto;
      background-color: #fff;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    form {
      display: flex;
      flex-direction: column;
    }

    label {
      font-weight: bold;
      margin-bottom: 5px;
    }

    input[type="text"],
    select {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      box-sizing: border-box;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    input[type="submit"] {
      background-color: #4caf50;
      color: white;
      padding: 10px 15px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }

    input[type="submit"]:hover {
      background-color: #45a049;
    }
  </style>
</head>
<body>
  <h1>New Food</h1>
  <div class="formcontainer">
    <%= form_with model: @food, url: foods_path, method: :post, local: true do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Chicken breasts" %>
      </div>
      <div>
        <%= f.label :measurement_unit %>
        <%= f.select :measurement_unit, options_for_select(["grams", "kilograms", "milligrams","Unit", "ounces", "pounds"]), placeholder: "Select a measurement unit" %>
      </div>
      <div>
        <%= f.label :price, "Price in $" %>
        <%= f.text_field :price, placeholder: "$ Enter the price" %>
      </div>
      <div>
        <%= f.label :quantity %>
        <%= f.text_field :quantity, placeholder: "Enter quantity" %>
      </div>
      <div>
        <%= f.submit "Add food" %>
      </div>
    <% end %>
  </div>
</body>
</html>