config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'foods#index'

  resources :foods, only: [:index, :new, :create, :destroy]

  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :recipes, except: [:update] do
    member do
      patch 'toggle_public'
      patch 'update_times'
      get 'new_step', to: 'recipe_steps#new'
      post 'create_step', to: 'recipe_steps#create'
    end

    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end

  get 'general_shopping_list', to: 'foods#general_shopping_list', as: 'general_shopping_list'

  resources :public_recipes, only: [:index]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_food_recipe, except: %i[edit destroy]

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Ingredient was successfully added.'
    else
      flash[:alert] = @recipe_food.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:recipe_id])
    @recipe = @recipe_food.recipe

    if @recipe_food
      # render 'edit'
    else
      flash[:alert] = 'Recipe food not found'
      redirect_to recipe_path(@recipe.id)
    end
  end

  def destroy
    puts 'youu'
    @recipe_food = RecipeFood.find(params[:recipe_id])
    @recipe = @recipe_food.recipe

    if @recipe_food.destroy
      flash[:success] = 'Recipe_food deleted successfully'
    else
      flash[:error] = 'Error: Recipe_food could not be deleted'
    end

    redirect_to recipe_path(params[:recipe_id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])

    if @recipe_food.update(update_food_params)
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Recipe food successfully updated.'
    else
      flash[:alert] = 'Failed to update recipe food'
      redirect_back_or_to root_path
    end
  end

  private

  def set_food_recipe
    @available_foods = Food.all
    @recipe = Recipe.find(params[:recipe_id])
  end

  def update_food_params
    params.require(:recipe_food).permit(:quantity)
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity, :recipe_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/edit.html.erb
<div class="formcontainer">
<h1 class="edit">Edit recipe food</h1>

<div>
<%= form_with model: @recipe_food, url: recipe_recipe_food_path(@recipe, @recipe_food), class: "formcontainer2", method: :patch do |f| %>
	     <div >
            <%= f.label :quantity %>
            <%= f.number_field :quantity, placeholder: 'New Quantity',  min: 0 %>
        </div>
        <div>
            <%= f.submit 'Update quantity' %>
        </div>
    <% end %>
</div>
<div>

app/views/recipe_foods/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
    }

    .formfood {
      max-width: 600px;
      margin: 50px auto;
      background-color: #fff;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h2 {
      text-align: center;
      color: #333;
    }

    .field {
      margin-bottom: 20px;
    }

    label {
      display: block;
      font-weight: bold;
      margin-bottom: 5px;
    }

    select,
    input[type="text"] {
      width: 100%;
      padding: 10px;
      box-sizing: border-box;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    input[type="submit"] {
      background-color: #4caf50;
      color: white;
      padding: 10px 15px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }

    input[type="submit"]:hover {
      background-color: #45a049;
    }
  </style>
</head>
<body>
  <div class='formfood'>
    <h2>Add a new ingredient</h2>
    <%= form_with(model: [@recipe, @recipe_food], url: recipe_recipe_foods_path(recipe_id: @recipe.id), local: true) do |f| %>
      <div class='field'>
        <%= f.label :food_id, 'Select food item' %>
        <%= f.collection_select(:food_id, @available_foods, :id, :name, {}, {}) %>
      </div>
      <div class='field'>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
      </div>

      <%= f.hidden_field :recipe_id, value: @recipe.id %>

      <div>
        <%= f.submit "Add ingredient" %>
      </div>
    <% end %>
  </div>
</body>
</html>